import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'getting-started', label: '👋 Start here'},
    {
      type: 'category',
      label: '🚀 Install kwatch',
      items: ['installation', 'kwatch-manager', 'kwatch-sh'],
    },
    {
      type: 'category',
      label: '📣 Alerts & channels',
      items: [
        'channels/channels',
        'channels/slack',
        'channels/discord',
        'channels/ms-teams',
        'channels/googlechat',
        'channels/telegram',
        'channels/email',
        'channels/pagerduty',
        'channels/opsgenie',
        'channels/zenduty',
        'channels/mattermost',
        'channels/rocketchat',
        'channels/matrix',
        'channels/dingtalk',
        'channels/feishu',
        'channels/webhook',
        'channels/providers',
        {
          type: 'category',
          label: '🧩 All provider guides',
          link: {type: 'doc', id: 'channels/providers'},
          items: [{type: 'autogenerated', dirName: 'channels/provider-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: '🎯 Monitors',
      items: [
        'general-configuration',
        'rollout-monitor-configuration',
        'daemonset-monitor-configuration',
        'job-monitor-configuration',
        'cronjob-monitor-configuration',
        'hpa-monitor-configuration',
        'heartbeat-monitor-configuration',
        'tls-monitor-configuration',
      ],
    },
    'cli-commands',
    {
      type: 'category',
      label: '🏗️ How kwatch works',
      items: [
        'architecture/target-architecture',
        'architecture/overview',
        'architecture/packages-overview',
        'architecture/correlation-and-alerting',
        'architecture/infrastructure-packages',
        'architecture/data-flow',
        'architecture/design-decisions',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Operations',
      items: [
        'operations/production-readiness',
        'operations/replication-and-failover',
        'operations/persistence-recovery',
        'operations/rbac-and-security',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: '📖 Reference',
      items: [
        {
          type: 'category',
          label: 'Generated reference',
          items: [
            'reference/generated/configuration',
            'reference/generated/providers',
            'reference/generated/features',
          ],
        },
        'kubernetes-coverage',
      ],
    },
    {
      type: 'category',
      label: '🤝 Contributing',
      items: [
        'contributing/contributing',
        'contributing/architecture-tour',
        'contributing/adding-monitor',
        'contributing/adding-provider',
        'contributing/documentation',
        'contributing/cloning-and-building',
        'contributing/github-workflow',
        'contributing/release-process',
      ],
    },
    {
      type: 'category',
      label: '📦 Release and trust',
      items: [
        'release/documentation-versioning',
        'release-integrity',
        'licensing',
        'third-party-notices',
        'trademarks',
      ],
    },
  ],
};

export default sidebars;
